CREATE TABLE ROOMS(
    ROOM_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(16) NOT NULL,
    ROOM_NUMBER CHAR(3) NOT NULL UNIQUE,
    BED_INFO CHAR(2) NOT NULL
);

CREATE TABLE GUESTS(
    GUEST_ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    EMAIL_ADDRESS VARCHAR(32),
    ADDRESS VARCHAR(16),
    COUNTRY VARCHAR(12),
    PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE RESERVATIONS(
    RESERVATION_ID BIGSERIAL PRIMARY KEY,
    ROOM_ID BIGINT NOT NULL,
    GUEST_ID BIGINT NOT NULL,
    RES_DATE DATE
);

ALTER TABLE RESERVATIONS ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID);
ALTER TABLE RESERVATIONS ADD FOREIGN KEY (GUEST_ID) REFERENCES GUESTS(GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATIONS(RES_DATE);